Add description in Thai (th)
Roshy10/taylors-version pull request #104
Opened 2023-10-28 06:55 UTC by melvinmcrn

2023-10-28 09:13 UTC, Roshy10 commented on src/locales/th.json
you'll need to add it to /src/i18n.js too for it to be used

2023-10-28 09:14 UTC, Roshy10 requested changes
you'll need to add it to /src/i18n.js too for it to be used

2023-10-28 19:40 UTC, melvinmcrn commented
Please review again. Thanks. @Roshy10

2023-10-30 10:32 UTC, Roshy10 commented
you seem to have added a selector in the footer, by default the language set in the browser will be used, so I don't think it's necessary to do that. It will also look a bit messy which I'm not keen on

Please also squash your commits

2023-10-30 10:33 UTC, Roshy10 requested changes
see comment above

2023-10-30 17:17 UTC, melvinmcrn commented
@Roshy10 all done. please review again.

2023-10-30 18:44 UTC, Roshy10 requested changes
make sure to revert the package json and package lock too

2024-05-27 04:57 UTC, closed without merging