Add 1989 tracks
Roshy10/taylors-version pull request #96
Opened 2023-10-27 06:57 UTC by ShamblesSM

- All 1989 tracks now point to their Taylor's Version.
- Wildest Dreams and This Love's Taylor's Versions now also point to the album version.
- Latest Update is now set to 1989.

2023-10-27 08:13 UTC, Roshy10 requested changes
Thanks for the PR! It looks like there's a few mistakes in the mappings unfortunately, so I can't let this through. Feel free to make another PR if you find I've missed anything

2023-10-27 08:13 UTC, Roshy10 commented on src/mappings/1989.js
> +            "spotify:track:1YYOx55cW5JfMe65zEHBdu",
wrong song: welcome to new york?

2023-10-27 08:13 UTC, Roshy10 commented on src/mappings/1989.js
> +            "spotify:track:5oID3Qj3tTCZEH9eo0snxm"
wrong track: shake it off

2023-10-27 08:13 UTC, Roshy10 commented on src/mappings/1989.js
> +    {
duplicate album

2023-10-27 12:15 UTC, ShamblesSM commented
darn, as I expected. i'll go fix those right now

2023-10-27 12:33 UTC, ShamblesSM commented
oops, I just realized you made a commit yourself already, feel free to close this if you wish, glad I could help with the initial thing tho despite the mistakes

2023-10-27 13:36 UTC, melvinmcrn commented
Hey @ShamblesSM , I just opened PR #98 which includes both updates from you and @Roshy10 .
Please feel free to review them too! :)

2023-10-28 16:03 UTC, Roshy10 commented
this is supercedded by PR#105, but thank you so much for your effort, I really appreciate it!

2023-10-28 16:03 UTC, closed without merging